#!/bin/bash
gpio mode 0 out
gpio mode 1 out
numFlips=0
numFlips=$1
flipSpeed=0
flipSpeed=$2
currentFlipNum=0
while [ $currentFlipNum -le $numFlips ]
do
	gpio write 0 1
	gpio write 1 0
	sleep $((flipSpeed / 100))
	gpio write 0 0
	gpio write 1 1
	sleep $((flipSpeed / 100))
	((currentFlipNum++))
done
